name: Deploy to Vercel (Preview)

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

concurrency:
  group: "deploy-preview-${{ github.ref }}"
  cancel-in-progress: true

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: G-W4PVVMT3PM

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup mise
        uses: jdx/mise-action@v2
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Build wasm
        working-directory: ./web-app
        run: pnpm build:wasm
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
