name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_BASE_PATH: /LGTMoon-rs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup mise
        uses: jdx/mise-action@v2
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Build wasm
        working-directory: ./web-app
        run: pnpm build:wasm
      - name: Install dependencies
        working-directory: ./web-app
        run: pnpm install --frozen-lockfile
      - name: Build with Next.js
        working-directory: ./web-app
        run: pnpm build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./web-app/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
