name: Renovate
on:
  schedule:
    - cron: '0/15 * * * *'
  pull_request:
    branches: main
    types: [opened, synchronize]
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.13
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
